#!/bin/bash

MyApp.weather() {
    echo "commands=weather show"
    dump-options
}

MyApp.cook() {
    echo "commands=cook"
    dump-options
}

MyApp.convert() {
    echo "commands=convert"
    dump-options
}

dump-options() {
    for i in "${!OPTIONS[@]}"
    do
        echo "option $i=${OPTIONS["$i"]}"
    done
}
