#!/bin/bash

MyApp.weather() {
    echo "commands=weather show"
    dump-options
#    if [[ ${OPTIONS["verbose"]} ]]; then
#        echo "It's rainy and cold =("
#    else
#        echo "rainy =("
#    fi
}

MyApp.cook() {
    echo "commands=cook"
    dump-options
#    local with="${OPTIONS["with"]}"
#    if [[ -n "$with" ]]; then
#        echo "cooking with $with"
#    else
#        echo "cooking"
#    fi
}

dump-options() {
    for i in "${!OPTIONS[@]}"
    do
        echo "option $i=${OPTIONS["$i"]}"
    done
}
